{% set name = "bamnostic" %}
{% set version = "1.2" %}
{% set sha256 = "8d7829223d8dab56505a62d6907d139c6b974806ee3269e7e3d3e390a186d911" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7

test:
  requires:
    - setuptools
  imports:
    - bamnostic

about:
  home: https://github.com/betteridiot/bamnostic
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a pure Python, OS-agnositic Binary Alignment Map (BAM) file parser and random access tool.

extra:
  recipe-maintainers:
    - betteridiot
    - ericmjl
